language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra
    - extra-android-support

script:
    - ./gradlew test

# http://docs.travis-ci.com/user/migrating-from-legacy/#tl%3Bdr
sudo: false
